-- Automated Homix News pipeline and Share Center news support.
-- Additive and safe to run before deploying either application.

BEGIN;

CREATE TABLE IF NOT EXISTS public.news_sources (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  source_key TEXT NOT NULL UNIQUE,
  name TEXT NOT NULL,
  source_type TEXT NOT NULL
    CHECK (source_type IN ('publisher_rss', 'google_news')),
  trust_tier TEXT NOT NULL CHECK (trust_tier IN ('A', 'B', 'C')),
  feed_url TEXT NOT NULL,
  publisher_domain TEXT,
  categories TEXT[] NOT NULL DEFAULT '{}',
  regions TEXT[] NOT NULL DEFAULT '{}',
  requires_corroboration BOOLEAN NOT NULL DEFAULT FALSE,
  enabled BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.news_candidates (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  source_id BIGINT REFERENCES public.news_sources(id) ON DELETE SET NULL,
  title TEXT NOT NULL,
  summary TEXT NOT NULL DEFAULT '',
  source_name TEXT NOT NULL,
  source_url TEXT NOT NULL,
  publisher_url TEXT,
  published_at TIMESTAMPTZ,
  discovered_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  category TEXT,
  region TEXT,
  content_hash TEXT NOT NULL UNIQUE,
  status TEXT NOT NULL DEFAULT 'new'
    CHECK (status IN ('new', 'selected', 'rejected', 'published')),
  rejection_reason TEXT,
  raw_payload JSONB NOT NULL DEFAULT '{}'::JSONB
);

CREATE INDEX IF NOT EXISTS idx_news_candidates_status_published
  ON public.news_candidates(status, published_at DESC);

CREATE TABLE IF NOT EXISTS public.news_articles (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  slug TEXT NOT NULL UNIQUE,
  candidate_id BIGINT UNIQUE
    REFERENCES public.news_candidates(id) ON DELETE SET NULL,
  status TEXT NOT NULL DEFAULT 'published'
    CHECK (status IN ('published', 'unpublished')),
  category TEXT NOT NULL
    CHECK (category IN ('market', 'policy', 'renting', 'buying', 'selling', 'investing', 'development')),
  region TEXT NOT NULL DEFAULT 'New York Metro',
  title_en TEXT NOT NULL,
  title_zh TEXT NOT NULL,
  summary_en TEXT NOT NULL,
  summary_zh TEXT NOT NULL,
  body_en TEXT NOT NULL,
  body_zh TEXT NOT NULL,
  homix_take_en TEXT NOT NULL,
  homix_take_zh TEXT NOT NULL,
  source_name TEXT NOT NULL,
  source_url TEXT NOT NULL,
  source_published_at TIMESTAMPTZ,
  published_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_news_articles_published
  ON public.news_articles(status, published_at DESC);

CREATE TABLE IF NOT EXISTS public.news_ingestion_runs (
  run_date DATE PRIMARY KEY,
  status TEXT NOT NULL
    CHECK (status IN ('running', 'published', 'skipped_no_candidate', 'failed')),
  started_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  finished_at TIMESTAMPTZ,
  fetched_count INTEGER NOT NULL DEFAULT 0,
  qualified_count INTEGER NOT NULL DEFAULT 0,
  article_id BIGINT REFERENCES public.news_articles(id) ON DELETE SET NULL,
  message TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE OR REPLACE FUNCTION public.claim_news_ingestion_run(
  p_run_date DATE,
  p_stale_after INTERVAL DEFAULT INTERVAL '30 minutes'
)
RETURNS BOOLEAN
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  affected_rows INTEGER;
BEGIN
  INSERT INTO public.news_ingestion_runs (run_date, status)
  VALUES (p_run_date, 'running')
  ON CONFLICT (run_date) DO NOTHING;
  GET DIAGNOSTICS affected_rows = ROW_COUNT;
  IF affected_rows = 1 THEN
    RETURN TRUE;
  END IF;

  UPDATE public.news_ingestion_runs
  SET status = 'running',
      started_at = NOW(),
      finished_at = NULL,
      fetched_count = 0,
      qualified_count = 0,
      article_id = NULL,
      message = NULL,
      updated_at = NOW()
  WHERE run_date = p_run_date
    AND (
      status = 'failed'
      OR (status = 'running' AND started_at < NOW() - p_stale_after)
    );
  GET DIAGNOSTICS affected_rows = ROW_COUNT;
  RETURN affected_rows = 1;
END;
$$;

REVOKE ALL ON FUNCTION public.claim_news_ingestion_run(DATE, INTERVAL)
  FROM PUBLIC, anon, authenticated;

ALTER TABLE public.news_sources ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.news_candidates ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.news_articles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.news_ingestion_runs ENABLE ROW LEVEL SECURITY;

DO $$ BEGIN
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'service_role') THEN
    GRANT SELECT, INSERT, UPDATE, DELETE
      ON public.news_sources,
         public.news_candidates,
         public.news_articles,
         public.news_ingestion_runs
      TO service_role;
    GRANT USAGE, SELECT
      ON SEQUENCE public.news_sources_id_seq,
                  public.news_candidates_id_seq,
                  public.news_articles_id_seq
      TO service_role;
    GRANT EXECUTE
      ON FUNCTION public.claim_news_ingestion_run(DATE, INTERVAL)
      TO service_role;
  END IF;
END $$;

INSERT INTO public.news_sources
  (source_key, name, source_type, trust_tier, feed_url, publisher_domain, categories, regions, requires_corroboration)
VALUES
  ('nyc-council', 'New York City Council', 'publisher_rss', 'A', 'https://council.nyc.gov/press/feed/', 'council.nyc.gov', ARRAY['policy','development'], ARRAY['New York City'], FALSE),
  ('bisnow-ny', 'Bisnow New York', 'publisher_rss', 'B', 'https://www.bisnow.com/rss-feed/new-york', 'bisnow.com', ARRAY['market','development','investing'], ARRAY['New York City'], FALSE),
  ('housingwire', 'HousingWire', 'publisher_rss', 'B', 'https://www.housingwire.com/feed/', 'housingwire.com', ARRAY['market','buying','selling'], ARRAY['United States'], FALSE),
  ('google-nyc-housing', 'Google News — NYC housing', 'google_news', 'C', 'https://news.google.com/rss/search?q=%28NYC%20OR%20%22New%20York%20City%22%29%20%28housing%20OR%20real%20estate%20OR%20rent%20OR%20zoning%29&hl=en-US&gl=US&ceid=US%3Aen', 'news.google.com', ARRAY['market','policy','renting','development'], ARRAY['New York City'], TRUE),
  ('google-ny-metro', 'Google News — New York metro housing', 'google_news', 'C', 'https://news.google.com/rss/search?q=%28%22Long%20Island%22%20OR%20%22North%20Jersey%22%20OR%20Westchester%29%20%28housing%20OR%20real%20estate%29&hl=en-US&gl=US&ceid=US%3Aen', 'news.google.com', ARRAY['market','buying','selling'], ARRAY['Long Island','New Jersey','Westchester'], TRUE)
ON CONFLICT (source_key) DO UPDATE SET
  name = EXCLUDED.name,
  source_type = EXCLUDED.source_type,
  trust_tier = EXCLUDED.trust_tier,
  feed_url = EXCLUDED.feed_url,
  publisher_domain = EXCLUDED.publisher_domain,
  categories = EXCLUDED.categories,
  regions = EXCLUDED.regions,
  requires_corroboration = EXCLUDED.requires_corroboration,
  updated_at = NOW();

UPDATE public.news_sources
SET enabled = FALSE, updated_at = NOW()
WHERE source_key IN ('therealdeal-ny', 'therealdeal-tristate');

DO $$ BEGIN
  IF to_regclass('public.share_links') IS NOT NULL THEN
    ALTER TABLE public.share_links
      DROP CONSTRAINT IF EXISTS share_links_content_kind_check;
    ALTER TABLE public.share_links
      ADD CONSTRAINT share_links_content_kind_check
      CHECK (content_kind IN ('listing', 'neighborhood', 'community', 'development', 'guide', 'news'));
  END IF;
END $$;

COMMIT;
