-- Homix Share Center schema.
-- Run after the Portal's portal.agents table exists. This is the same additive
-- migration as homixliving/db/migrations/20260729-share-center.sql.

BEGIN;

CREATE TABLE IF NOT EXISTS public.share_links (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  code TEXT NOT NULL UNIQUE,
  agent_id INTEGER NOT NULL REFERENCES portal.agents(id) ON DELETE CASCADE,
  content_kind TEXT NOT NULL
    CHECK (content_kind IN ('listing', 'neighborhood', 'community', 'development', 'guide', 'news')),
  content_key TEXT NOT NULL,
  content_path TEXT NOT NULL,
  content_title TEXT NOT NULL,
  content_subtitle TEXT,
  content_image TEXT,
  locale TEXT NOT NULL DEFAULT 'zh'
    CHECK (locale IN ('en', 'zh')),
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (agent_id, content_kind, content_key, locale)
);

CREATE INDEX IF NOT EXISTS idx_share_links_agent_created
  ON public.share_links(agent_id, created_at DESC);

CREATE TABLE IF NOT EXISTS public.share_visits (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  share_link_id INTEGER NOT NULL
    REFERENCES public.share_links(id) ON DELETE CASCADE,
  session_key TEXT NOT NULL UNIQUE,
  visitor_hash TEXT NOT NULL,
  referrer_domain TEXT,
  device_type TEXT,
  active_seconds INTEGER NOT NULL DEFAULT 0 CHECK (active_seconds >= 0),
  max_scroll_depth INTEGER NOT NULL DEFAULT 0
    CHECK (max_scroll_depth BETWEEN 0 AND 100),
  started_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  last_seen_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_share_visits_link_started
  ON public.share_visits(share_link_id, started_at DESC);
CREATE INDEX IF NOT EXISTS idx_share_visits_link_visitor
  ON public.share_visits(share_link_id, visitor_hash);

CREATE TABLE IF NOT EXISTS public.share_events (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  share_link_id INTEGER NOT NULL
    REFERENCES public.share_links(id) ON DELETE CASCADE,
  visit_id INTEGER REFERENCES public.share_visits(id) ON DELETE SET NULL,
  event_type TEXT NOT NULL
    CHECK (event_type IN ('call', 'email', 'wechat', 'profile', 'inquiry')),
  metadata JSONB,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_share_events_link_created
  ON public.share_events(share_link_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_share_events_type_created
  ON public.share_events(event_type, created_at DESC);

ALTER TABLE public.share_links ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.share_visits ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.share_events ENABLE ROW LEVEL SECURITY;

DO $$ BEGIN
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'service_role') THEN
    GRANT SELECT, INSERT, UPDATE, DELETE
      ON public.share_links, public.share_visits, public.share_events
      TO service_role;
    GRANT USAGE, SELECT
      ON SEQUENCE public.share_links_id_seq,
                  public.share_visits_id_seq,
                  public.share_events_id_seq
      TO service_role;
  END IF;
END $$;

ALTER TABLE public.inquiries
  ADD COLUMN IF NOT EXISTS share_link_id INTEGER
    REFERENCES public.share_links(id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS referred_agent_id INTEGER
    REFERENCES portal.agents(id) ON DELETE SET NULL;

CREATE INDEX IF NOT EXISTS idx_inquiries_share_link
  ON public.inquiries(share_link_id)
  WHERE share_link_id IS NOT NULL;

COMMIT;
