import type { JournalPost } from "./posts";
import { SITE_MEDIA_ROOT } from "@/lib/media";

export const priorityEvergreenPosts: JournalPost[] = [
  {
    slug: "selling-process-new-york",
    date: "2026-07-30",
    contentKind: "evergreen",
    topic: "selling",
    parentGuideSlug: "selling-in-new-york",
    authorSlug: "sunny",
    cover: `${SITE_MEDIA_ROOT}/journal/covers/brownstone.jpg`,
    readMinutes: 7,
    category: { en: "Seller Guide", zh: "卖房指南" },
    title: {
      en: "Selling in New York: From Pricing to Closing",
      zh: "纽约卖房全流程：从定价到过户",
    },
    excerpt: {
      en: "The decisions, documents, and handoffs that turn a listing into a completed New York sale.",
      zh: "把挂牌顺利推进到完成过户所需的决策、文件和协作节点。",
    },
    body: {
      en: "## Before the listing\n\nChoose your attorney and agent early, then assemble ownership, mortgage, building, alteration, permit, and occupancy records. Resolve issues that could stop diligence before a buyer discovers them. Prepare the home for the buyer you expect, not for your own taste: repair material defects, reduce clutter, improve light, and make every room's purpose obvious.\n\n## Pricing and launch\n\nPrice from recent closed sales, adjusted for property type, condition, floor, view, layout, outdoor space, carrying cost, and current competition. Active listings show today's alternatives; expired listings show what buyers rejected. Photography, floor plans, copy, and launch timing should all be ready before the listing appears.\n\n## Offer through contract\n\nCompare price together with financing, down payment, contingencies, appraisal exposure, closing schedule, and the buyer's readiness. Once an offer is accepted, New York attorneys conduct diligence and negotiate the contract. An accepted offer is generally not a signed contract, so keep the process moving and avoid assuming the sale is final.\n\n## Contract through closing\n\nTrack the deposit, financing commitment, appraisal, title or building review, board package where applicable, final walk-through, payoff, and closing statement. Ask your attorney and accountant for a property-specific estimate of transfer taxes, building charges, mortgage payoff, commission, and other deductions before planning how to use the proceeds.\n\n*Educational information only; confirm legal, tax, building, and transaction requirements with licensed professionals.*",
      zh: "## 挂牌之前\n\n尽早确定律师和经纪人，并整理产权、贷款、大楼、装修、许可和入住文件。在买家尽调前先解决可能阻断交易的问题。房屋准备要面向目标买家，而不是卖家自己的审美：修复实质缺陷、减少杂物、改善采光，让每个空间的用途清楚。\n\n## 定价与上市\n\n从近期已成交案例出发，再按物业类型、房况、楼层、景观、户型、户外空间、持有成本和当前竞争调整。在售房源说明买家今天还有什么选择，撤牌房源则说明市场拒绝了什么。摄影、户型图、文案和发布时间应在挂牌前一次准备到位。\n\n## 报价到合同\n\n同时比较价格、贷款、首付、附带条件、估价风险、过户时间和买家材料准备度。接受报价后，纽约双方律师会进行尽调并协商合同。接受报价通常不等于已经签约，因此要持续推进，不能过早把交易视为完成。\n\n## 合同到过户\n\n逐项跟踪定金、贷款承诺、估价、产权或大楼审查、适用时的董事会材料、最终验房、贷款结清和 closing statement。在安排卖房款用途前，应让律师和会计师针对该物业估算转让税、大楼费用、贷款余额、佣金和其他扣项。\n\n*仅供教育参考；法律、税务、大楼和交易要求请由持牌专业人士确认。*",
    },
  },
  {
    slug: "pricing-when-comps-disagree",
    date: "2026-07-30",
    contentKind: "evergreen",
    topic: "selling",
    parentGuideSlug: "selling-in-new-york",
    authorSlug: "sunny",
    cover: `${SITE_MEDIA_ROOT}/journal/covers/upper-west.jpg`,
    readMinutes: 5,
    category: { en: "Seller Guide", zh: "卖房指南" },
    title: {
      en: "How to Price When Comparable Sales Disagree",
      zh: "可比成交互相矛盾时，房子应该怎么定价",
    },
    excerpt: {
      en: "A range-based method for reading imperfect comps without cherry-picking the highest sale.",
      zh: "用区间和调整项读懂不完美的可比成交，而不是只挑最高价。",
    },
    body: {
      en: "Comparable sales rarely line up perfectly. Start by separating property type and micro-location, then favor recent arm's-length closings with similar size and layout. Adjust one difference at a time: condition, floor, light, view, outdoor space, monthly carrying cost, building services, and renovation quality.\n\nBuild a **defensible range**, not a single magic number. The lower end should reflect a faster, lower-risk launch; the upper end should require clear evidence that the property is superior. Active listings are competition, not proof of value, and expired listings are evidence that a price failed.\n\nFinally, compare the list-price strategy with the seller's timing and risk tolerance. A price that maximizes showings can create competition; a test-the-market price may require more time and future reductions. The right answer is the one whose assumptions can be explained and updated when real buyer feedback arrives.",
      zh: "可比成交几乎不会完全一致。先按物业类型和微观位置分组，再优先采用近期、正常市场条件下成交且面积与户型接近的案例。每次只调整一个差异：房况、楼层、采光、景观、户外空间、月度持有成本、大楼服务和装修质量。\n\n应建立一个**可以解释的价格区间**，而不是寻找神奇的单一数字。区间下沿代表更快、风险更低的上市策略；上沿则必须有明确证据证明物业确实更优。在售房源只是竞争，不是价值证明；撤牌房源反而说明某个价格未被接受。\n\n最后把挂牌策略与卖家的时间和风险偏好放在一起。吸引更多看房的定价可能形成竞争，试探市场的高价则可能需要更长时间和后续降价。合理答案应能解释每个假设，并根据真实买家反馈及时更新。",
    },
  },
  {
    slug: "highest-offer-not-always-best",
    date: "2026-07-30",
    contentKind: "evergreen",
    topic: "selling",
    parentGuideSlug: "selling-in-new-york",
    authorSlug: "sunny",
    cover: `${SITE_MEDIA_ROOT}/journal/covers/midtown.jpg`,
    readMinutes: 5,
    category: { en: "Seller Guide", zh: "卖房指南" },
    title: {
      en: "Why the Highest Offer Is Not Always the Best Offer",
      zh: "为什么最高报价不一定是最好的报价",
    },
    excerpt: {
      en: "How sellers should compare certainty, timing, contingencies, and true net proceeds.",
      zh: "卖家应如何比较成交把握、时间、附带条件与真实净到手。",
    },
    body: {
      en: "A strong offer is a package. Compare the proposed price with financing type, down payment, proof of funds, lender readiness, appraisal exposure, inspection and financing contingencies, requested credits, closing date, and any post-closing occupancy.\n\nCalculate **net proceeds**, not just headline price. A buyer who asks for a large credit, needs the property to appraise above the strongest comps, or has a fragile financing timeline may deliver less certainty than a slightly lower buyer with verified funds and clean terms.\n\nFor a co-op, board readiness is also transaction risk. For a house or condo, title, inspection, and appraisal conditions may matter more. Ask for a side-by-side summary and let your attorney review unusual terms. The objective is not to avoid all risk; it is to be paid appropriately for the risk you accept.",
      zh: "一份可靠报价是一个完整方案。比较出价时，要同时查看贷款类型、首付、资金证明、贷款机构进度、估价风险、验房和贷款附带条件、买家要求的 credit、过户日期以及交割后占用安排。\n\n要算的是**净到手**，而不是标题金额。要求大额 credit、必须高于最强可比成交才能通过估价，或贷款时间非常脆弱的买家，确定性可能不如资金已核实、条款干净但金额略低的买家。\n\nCo-op 还要评估董事会材料能力；独栋和 Condo 则更可能受到产权、验房与估价条件影响。应让经纪人制作并列比较表，并由律师审查异常条款。目标不是消除全部风险，而是让卖家为承担的风险得到合理补偿。",
    },
  },
  {
    slug: "pre-listing-repairs-vs-as-is",
    date: "2026-07-30",
    contentKind: "evergreen",
    topic: "selling",
    parentGuideSlug: "selling-in-new-york",
    authorSlug: "sunny",
    cover: `${SITE_MEDIA_ROOT}/journal/covers/construction.jpg`,
    readMinutes: 5,
    category: { en: "Seller Guide", zh: "卖房指南" },
    title: {
      en: "Repair, Renovate, or Sell As-Is?",
      zh: "卖房前应该维修、装修，还是按现状出售",
    },
    excerpt: {
      en: "A practical way to separate value-protecting repairs from expensive cosmetic projects.",
      zh: "区分保护价值的必要维修和昂贵审美工程的实用方法。",
    },
    body: {
      en: "Start with defects that create fear or stop diligence: active leaks, unsafe electrical conditions, non-working systems, pests, mold concerns, permit problems, and obvious deferred maintenance. Buyers discount uncertainty more aggressively than a known repair cost.\n\nNext address low-cost presentation: deep cleaning, decluttering, neutral paint where needed, working bulbs, simple hardware, and minor repairs. These changes help photography and make the property easier to understand without committing to a full renovation.\n\nLarge cosmetic projects require a return test. Estimate cost, delay, carrying expense, permit risk, and the value of letting a buyer choose finishes. An as-is sale can be rational when speed matters or the likely buyer plans a full renovation — but disclose known material facts as required and price the condition honestly.",
      zh: "先处理会制造恐惧或阻断尽调的问题：持续渗漏、不安全电路、设备失灵、虫害、霉菌疑虑、许可问题和明显失修。买家对“不确定性”的折价，往往高于已知维修成本本身。\n\n接着处理低成本展示：深度清洁、减少杂物、必要时使用中性油漆、保证灯具工作、更换简单五金和完成小维修。这些改动能提升摄影效果，也让买家更容易理解空间，无需承担整套装修。\n\n大型审美工程必须做回报测试：计算造价、延期、持有成本、许可风险，以及让买家自己选择材料的价值。如果卖家重视速度，或目标买家本来就计划全面装修，按现状出售完全合理；但仍要按要求披露已知的重要事实，并诚实反映房况。",
    },
  },
  {
    slug: "monthly-cost-beyond-purchase-price",
    date: "2026-07-30",
    contentKind: "evergreen",
    topic: "buying",
    parentGuideSlug: "buying-in-nyc",
    authorSlug: "sunny",
    cover: `${SITE_MEDIA_ROOT}/journal/covers/financial-district.jpg`,
    readMinutes: 6,
    category: { en: "Buyer Guide", zh: "买房指南" },
    title: {
      en: "The Monthly Cost Beyond the Purchase Price",
      zh: "买价之外：真正的每月持有成本怎么算",
    },
    excerpt: {
      en: "Mortgage, tax, maintenance, insurance, assessments, and reserves belong in one budget.",
      zh: "把贷款、税、管理费、保险、assessment 和储备放进同一份预算。",
    },
    body: {
      en: "Begin with principal and interest, then add property tax, condo common charges or co-op maintenance, homeowner insurance, mortgage insurance where applicable, utilities, parking, and any current assessment. Co-op maintenance may include portions of the building's tax and underlying mortgage, so it should not be compared directly with a condo common charge without reading the details.\n\nAdd a reserve for repairs and future building costs. Review financial statements, reserve levels, recent assessments, insurance changes, planned capital work, and the history of fee increases. A low monthly charge can be misleading if the building has deferred work or weak reserves.\n\nThen stress-test the budget: a rate change before lock, a tax or maintenance increase, an assessment, or a temporary income interruption. The affordable home is the one whose complete monthly cost still leaves room for savings and ordinary life.",
      zh: "先算贷款本金与利息，再加房产税、Condo common charge 或 Co-op maintenance、房屋保险、适用时的贷款保险、水电、停车和当前 assessment。Co-op maintenance 可能包含大楼房产税和底层贷款的一部分，因此不能在不了解构成时直接和 Condo common charge 比较。\n\n还要为室内维修和未来大楼支出留储备。审查财务报表、储备金、近期 assessment、保险变化、计划中的资本工程以及费用上涨历史。月费很低未必是好事，如果大楼积压维修或储备不足，未来成本可能集中出现。\n\n最后进行压力测试：锁定利率前发生变化、税或管理费上涨、新增 assessment，或收入暂时中断。真正买得起的房子，是把所有月度成本算完后，仍能保留储蓄和正常生活空间的房子。",
    },
  },
  {
    slug: "inspection-appraisal-negotiation",
    date: "2026-07-30",
    contentKind: "evergreen",
    topic: "buying",
    parentGuideSlug: "buying-in-nyc",
    authorSlug: "sunny",
    cover: `${SITE_MEDIA_ROOT}/journal/covers/apartment-building.jpg`,
    readMinutes: 6,
    category: { en: "Buyer Guide", zh: "买房指南" },
    title: {
      en: "Inspection, Appraisal, and Negotiation Are Different",
      zh: "验房、估价和谈判是三件不同的事",
    },
    excerpt: {
      en: "What each checkpoint is designed to answer, and why one cannot replace another.",
      zh: "每个环节分别回答什么问题，以及为什么彼此不能替代。",
    },
    body: {
      en: "An **inspection** evaluates physical condition and helps identify safety issues, defects, maintenance, and future repairs. Its scope depends on property type; a condo inspection is not the same as a house inspection, and building systems may sit outside the unit.\n\nAn **appraisal** is generally ordered for the lender to support collateral value. It is not a warranty of condition and does not replace inspection or legal diligence. A property can appraise and still have costly defects; it can also be in sound condition and appraise below the contract price.\n\n**Negotiation** uses the contract, market, inspection findings, appraisal result, and each side's leverage. Not every finding justifies a credit, and not every low appraisal ends a deal. Before bidding, understand which contingencies protect you, their deadlines, and what happens if the parties cannot agree.",
      zh: "**验房**评估物业的物理状况，帮助发现安全问题、缺陷、维护情况和未来维修。范围会随物业类型变化：Condo 单元验房和独栋验房不同，大楼公共系统也可能不在单元验房范围内。\n\n**估价**通常由贷款方安排，用于支持抵押物价值。它不是房况保证，也不能替代验房或法律尽调。房子可以顺利通过估价却存在昂贵缺陷，也可能房况良好但估价低于合同价。\n\n**谈判**综合合同、市场、验房结果、估价和双方筹码。不是每个验房发现都能换来 credit，也不是每次低估价都会终止交易。出价前应理解哪些附带条件保护自己、各自的截止时间，以及双方无法达成一致时会发生什么。",
    },
  },
  {
    slug: "sell-and-buy-at-the-same-time",
    date: "2026-07-30",
    contentKind: "evergreen",
    topic: "selling",
    secondaryTags: ["buying"],
    parentGuideSlug: "selling-in-new-york",
    authorSlug: "sunny",
    cover: `${SITE_MEDIA_ROOT}/journal/covers/park-slope.jpg`,
    readMinutes: 6,
    category: { en: "Seller & Buyer Guide", zh: "买卖衔接指南" },
    title: {
      en: "How to Sell and Buy at the Same Time",
      zh: "如何在同一阶段卖房又买房",
    },
    excerpt: {
      en: "Three sequencing strategies for deposits, financing, occupancy, and moving risk.",
      zh: "围绕定金、融资、交割和搬家的三种买卖衔接策略。",
    },
    body: {
      en: "There are three basic sequences. **Sell first** creates the clearest budget and strongest purchase funds but may require temporary housing. **Buy first** gives moving certainty but requires enough liquidity and borrowing capacity to carry two properties. **Coordinate both closings** can reduce the gap, but every legal, financing, and moving dependency must work on schedule.\n\nBefore choosing, ask a lender how the current mortgage, expected proceeds, bridge options, and debt-to-income rules affect approval. Ask both attorneys how deposits, contingencies, closing dates, possession, and a possible post-closing occupancy agreement would work. Never assume one closing's proceeds will be available for the other without written coordination.\n\nBuild a fallback budget for delay. Storage, short-term housing, rate-lock extensions, double carrying costs, and moving changes are cheaper to plan before they become emergencies.",
      zh: "基本有三种顺序。**先卖后买**能提供最清楚的预算和最可靠的购房资金，但可能需要临时住房；**先买后卖**让搬家更确定，却要求有足够流动性和贷款能力同时持有两套房；**协调同日或相近过户**可以缩短空档，但法律、贷款和搬家环节都必须按计划完成。\n\n决定前，应让贷款机构说明现有贷款、预计卖房款、过桥方案和债务收入比如何影响审批；让两边律师说明定金、附带条件、过户日期、交房和可能的交割后占用如何安排。没有书面协调时，不要假设一笔过户款一定能及时用于另一笔交易。\n\n还要为延期准备后备预算。仓储、短租、延长锁定利率、双重持有成本和改期搬家，如果提前规划，都比临时救火便宜。",
    },
  },
  {
    slug: "rental-property-cash-flow-new-york",
    date: "2026-07-30",
    contentKind: "evergreen",
    topic: "investing",
    parentGuideSlug: "investing-and-landlording",
    authorSlug: "sunny",
    cover: `${SITE_MEDIA_ROOT}/journal/covers/jersey-city.jpg`,
    readMinutes: 6,
    category: { en: "Investor Guide", zh: "投资指南" },
    title: {
      en: "Rental Property Cash Flow: A Conservative New York Model",
      zh: "纽约投资房现金流：一套保守测算方法",
    },
    excerpt: {
      en: "A repeatable way to move from advertised rent to durable after-debt cash flow.",
      zh: "从宣传租金推导到可持续贷后现金流的可复用方法。",
    },
    body: {
      en: "Start with lawful, supportable rent — an existing lease, rent roll, or conservative market comps. Subtract vacancy and credit loss before operating expenses. Then include property tax, insurance, common charges or maintenance, owner-paid utilities, management, leasing, routine repairs, and a capital reserve.\n\nThe result before debt is net operating income. Only then subtract loan payments to estimate cash flow. Keep acquisition costs, immediate repairs, and required reserves in the invested-cash denominator when comparing returns.\n\nRun at least three cases: base, rent downside with higher vacancy, and major repair. Do not count appreciation, refinancing, or future rent growth as money available to pay today's bills. If the investment fails without optimistic assumptions, the price or plan needs to change.",
      zh: "先采用合法且有依据的租金：现有租约、rent roll 或保守的市场可比租金。在营运支出前先扣除空置和坏账，再计入房产税、保险、common charge 或 maintenance、房东承担的水电、管理、招租、日常维修和资本开支储备。\n\n贷款前的结果是净营运收入，再扣除贷款本息才得到预计现金流。比较回报时，买入交易成本、立即维修和必要储备也应计入投入现金。\n\n至少测算基准、租金下行且空置上升、以及大修三种情景。不要把升值、再融资或未来涨租当作今天可以支付账单的钱。如果一笔投资离开乐观假设就无法成立，需要调整的是价格或计划。",
    },
  },
  {
    slug: "small-multifamily-holding-costs",
    date: "2026-07-30",
    contentKind: "evergreen",
    topic: "investing",
    parentGuideSlug: "investing-and-landlording",
    authorSlug: "sunny",
    cover: `${SITE_MEDIA_ROOT}/journal/covers/apartment-building.jpg`,
    readMinutes: 6,
    category: { en: "Investor Guide", zh: "投资指南" },
    title: {
      en: "Small Multifamily Costs Buyers Commonly Miss",
      zh: "小型多户住宅最容易漏算的持有成本",
    },
    excerpt: {
      en: "Utilities, legal units, turnover, systems, compliance, and reserves beyond the rent roll.",
      zh: "租金表之外的水电、合法户数、换租、设备、合规与储备成本。",
    },
    body: {
      en: "A rent roll is only the income side. Confirm who pays heat, hot water, common electric, water and sewer, snow, landscaping, sanitation, and pest control. Review actual bills rather than estimating from a different building.\n\nVerify legal unit count and use against the certificate of occupancy and municipal records. An occupied basement or converted space is not automatically a lawful apartment. Review leases, deposits, rent history, violations, open permits, registrations, and required inspections with an attorney.\n\nBudget turnover, leasing, painting, appliances, roof, facade, boiler or HVAC, plumbing, electrical, insurance deductibles, and emergency response. Small buildings have fewer units across which to spread one large repair, so reserve discipline matters more, not less.",
      zh: "Rent roll 只反映收入一侧。要确认暖气、热水、公共区域电费、供水排污、除雪、园艺、垃圾和虫害分别由谁承担，并审查真实账单，而不是套用另一栋楼的估算。\n\n还要用入住许可和市政记录核实合法户数与用途。地下室有人居住或空间已经改造，不等于它是合法单元。应让律师审查租约、押金、租金历史、违规、未结许可、登记和法定检查。\n\n预算还应包括换租空档、招租、油漆、电器、屋顶、外墙、锅炉或 HVAC、管道、电路、保险免赔额和紧急维修。小楼可分摊一次大修的单元更少，所以更需要严格储备。",
    },
  },
  {
    slug: "rent-stabilized-free-market-landlord-basics",
    date: "2026-07-30",
    contentKind: "evergreen",
    topic: "investing",
    secondaryTags: ["policy"],
    parentGuideSlug: "investing-and-landlording",
    authorSlug: "sunny",
    cover: `${SITE_MEDIA_ROOT}/journal/covers/city-hall.jpg`,
    readMinutes: 6,
    category: { en: "Landlord Guide", zh: "房东指南" },
    title: {
      en: "Rent-Stabilized and Free-Market Units: Start With the Records",
      zh: "租金稳定单元与自由市场单元：先从记录核实",
    },
    excerpt: {
      en: "Why unit status, rent history, registrations, and leases must be verified before underwriting.",
      zh: "为什么测算前必须核实单元状态、租金历史、登记与租约。",
    },
    body: {
      en: "Do not determine a unit's regulatory status from the current rent, listing language, or a seller's informal statement. Ask counsel to review the building, unit history, registrations, leases, improvements, occupancy, and applicable law. A unit may require analysis even when the current rent appears high.\n\nFor any occupied property, underwrite the lease that legally exists — not an assumed future rent. Review renewal obligations, notice periods, deposits, service requirements, records, and succession or occupancy issues where relevant. Free-market status does not remove fair-housing, habitability, building-code, deposit, or notice obligations.\n\nRegulation changes, and remedies for mistakes can be significant. Treat legal review and ongoing recordkeeping as normal operating costs, not optional paperwork.\n\n*General educational information, not legal advice. Obtain current guidance from a New York landlord-tenant attorney and the relevant housing agencies.*",
      zh: "不要根据当前租金、挂牌文案或卖家的口头说法判断单元监管状态。应由律师审查楼宇与单元历史、登记、租约、装修、入住情况和适用法律。即使当前租金看起来很高，单元仍可能需要进一步分析。\n\n购买带租客物业时，应按**法律上真实存在的租约**测算，而不是假设未来可以收多少租金。审查续租义务、通知期限、押金、服务要求、记录，以及适用时的继承权或入住问题。自由市场状态也不会免除公平住房、适住性、建筑规范、押金和通知义务。\n\n法规会变化，错误处理的后果可能很大。法律审查和持续记录应视为正常经营成本，而不是可选文书。\n\n*仅供一般教育参考，不构成法律意见。请向纽约房东租客律师及相关住房机构获取最新指导。*",
    },
  },
];
